[package]
name = "netman"
version = "0.1.0"
edition = "2024"

[dependencies]
rtnetlink = "0.21.0"
mozim = "0.3.2"

tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "io-std", "sync", "signal", "time"] }
futures-util = "0.3"

anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bin]]
name = "nmctl"
path = "src/bin/nmctl.rs"
